###
# ansible-playbook deploy-evobackup-beta.yml -K --diff -l HOSTNAME --check
#
---

- name: Deploy a beta version of evobackup
  hosts: all
  gather_facts: true
  become: true

  vars:
    evobackup_script_path: /etc/cron.daily/zzz_evobackup_beta
    evobackup_mail: alert4@evolix.net
    evobackup_libdir: "/usr/local/lib/evobackup"

  tasks:
    - name: LIBDIR is present
      file:
        path: "{{ evobackup_libdir }}"
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: libraries are installed
      copy:
        src: "{{ item }}"
        dest: "{{ evobackup_libdir }}/"
        remote_src: false
        owner: root
        group: root
        mode: "0644"
        force: true
      loop: "{{ lookup('fileglob', 'lib/*.sh', wantlist=True) }}"

    - name: script is present
      copy:
        src: zzz_evobackup
        dest: "{{ evobackup_script_path }}"
        remote_src: false
        owner: root
        group: root
        mode: "0750"
        force: false

    - name: Email is customized
      replace:
        dest: "{{ evobackup_script_path }}"
        regexp: "^MAIL=.*"
        replace: "MAIL={{ evobackup_mail }}"

    - name: LIBDIR is customized
      replace:
        dest: "{{ evobackup_script_path }}"
        regexp: "^LIBDIR=.*"
        replace: "LIBDIR=\"{{ evobackup_libdir }}\""