#!/bin/sh
# Get system informations.

# Extract MBR / table partitions.
# dd if=/dev/sda of=/home/backup/MBR bs=512 count=1 2>&1 | egrep -v "(records
# in|records out|512 bytes)"
# sfdisk -d /dev/sda > /home/backup/partitions 2>&1 | egrep -v "(Warning:
#extended partition does not start at a cylinder boundary|DOS and Linux will
# interpret the contents differently)"

# Get routes
# traceroute -n 8.8.8.8 > /home/backup/traceroute-8.8.8.8
# mtr -r 8.8.8.8 > /home/backup/mtr-8.8.8.8
# traceroute -n backup.evolix.net > /home/backup/traceroute-backup.evolix.net
# mtr -r backup.evolix.net > /home/backup/mtr-backup.evolix.net
# traceroute -n www.evolix.fr > /home/backup/traceroute-www.evolix.fr
# mtr -r www.evolix.fr > /home/backup/mtr-www.evolix.fr
# traceroute -n www.evolix.net > /home/backup/traceroute-www.evolix.net
# mtr -r www.evolix.net > /home/backup/mtr-www.evolix.net

# Process list.
ps auwwwx > /home/backup/process.txt

# Network connections list.
netstat -taupen > /home/backup/netstat.txt

# Packages list.
dpkg -l > /home/backup/packages.txt

exit 0