kind: pipeline
name: default

steps:
- name: build debian package
  image: vlaborie/gbp:latest
  branches:
  - debian
  commands:
  - mk-build-deps --install --remove debian/control
  - gbp buildpackage
  volumes:
  - name: tmp
    path: /tmp
  when:
    branch:
    - debian

- name: upload debian package
  image: drillster/drone-rsync
  settings:
    hosts: ["pub.evolix.net"]
    port: 22
    user: droneci
    key:
      from_secret: drone_private_key
    target: /home/droneci/bkctld/
    source: /tmp/bkctld/
    delete: true
  volumes:
  - name: tmp
    path: /tmp
  when:
    branch:
    - debian

volumes:
- name: tmp
  host:
    path: /tmp
