kind: pipeline
name: default

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: build debian package
  image: evolix/gbp:bullseye
  branches:
  - debian
  commands:
  - mk-build-deps --install --remove debian/control
  - git clean --force
  - gbp buildpackage -us -uc
  when:
    branch:
    - debian

- name: upload debian package
  image: drillster/drone-rsync
  settings:
    hosts: ["pub.evolix.net"]
    port: 22
    user: droneci
    key:
      from_secret: drone_private_key
    target: /home/droneci/bkctld/
    source: ../bkctld*
    delete: true
  when:
    branch:
    - debian
