#!/bin/sh

### BEGIN INIT INFO
# Provides:             evobackup
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2
# Default-Stop:         1
# Short-Description:    evobackup jails
### END INIT INFO

set -e

case "$1" in
    start)
    ;;

    stop)
    ;;

    reload|force-reload)
    ;;

    restart)
    ;;
esac

exit 0

