#!/bin/sh
#
# Make and display stats on jails (size, lastconn)
# Usage: stats
#

LIBDIR="$(dirname $0)" && . "${LIBDIR}/config"

grep -qE " ${MOUNT_POINT} " /etc/mtab || error "Backup disk is not mounted !"

lsof "${IDX_FILE}" >/dev/null 2>&1 || nohup sh -s -- <<EOF >/dev/null 2>&1 &
ionice -c3 "${DUC}" index -e "*\.*" -d "${IDX_FILE}" "${MOUNT_POINT}"
touch "${MOUNT_POINT}/.lastrun.duc"
EOF
[ ! -f "${MOUNT_POINT}/.lastrun.duc" ] && notice "First run of DUC always in progress ..." && exit 0
[ ! -f ${IDX_FILE} ] && error "Index file do not exits !"
printf "Last update of index file : "
stat --format=%Y "${MOUNT_POINT}/.lastrun.duc" | xargs -i -n1 date -R -d "@{}"
echo "<jail> <size> <incs> <lastconn>" | awk '{ printf("%- 30s %- 10s %- 10s %- 15s\n", $1, $2, $3, $4); }'
duc_output=$(mktemp)
stat_output=$(mktemp)
incs_output=$(mktemp)
trap "rm ${duc_output} ${incs_output} ${stat_output}" 0
"${DUC}" ls -d "${IDX_FILE}" "${MOUNT_POINT}" > "${duc_output}"
awk '{ print $2 }' "${duc_output}" | while read jail; do
    stat --format=%Y "${LOGDIR}/${jail}/lastlog" | xargs -i -n1 date -d "@{}" "+%d-%m-%Y" >> "${stat_output}"
    inc=0
    if [ -f "${CONFDIR}/${jail}" ]; then
        day=$(grep -c "day" "${CONFDIR}/${jail}")
        month=$(grep -c "month" "${CONFDIR}/${jail}")
        inc="${day}/${month}"
    fi
    echo "${inc}" >> "${incs_output}"
done
paste "${duc_output}" "${incs_output}" "${stat_output}" | awk '{ printf("%- 30s %- 10s %- 10s %- 15s\n", $2, $1, $3, $4); }'
