#!/bin/sh
#
# Run check on jails (NRPE output)
# Usage: check
#

# shellcheck source=lib/config
LIBDIR="$(dirname $0)" && . "${LIBDIR}/config"

return=0
nb_crit=0
nb_warn=0
nb_ok=0
nb_unkn=0
output=""

DEFAULT_CRITICAL="${CRITICAL}"
DEFAULT_WARNING="${WARNING}"

if [ -b "${BACKUP_DISK}" ]; then
    cryptsetup isLuks "${BACKUP_DISK}"
    if [ "$?" -eq 0 ]; then
        if [ ! -b '/dev/mapper/backup' ]; then
            echo "Luks disk ${BACKUP_DISK} is not mounted !\n"
            echo "cryptsetup luksOpen ${BACKUP_DISK} backup"
            exit 2
        fi
        BACKUP_DISK='/dev/mapper/backup'
    fi
    grep -qE "^${BACKUP_DISK} " /etc/mtab
    if [ "$?" -ne 0 ]; then
         echo "Backup disk ${BACKUP_DISK} is not mounted !\n"
         echo "mount ${BACKUP_DISK} /backup"
         exit 2
    fi
fi

check_jail() {
    jail=$1

    cur_time=$(date "+%s")
    last_conn=$(stat --format=%Y "${JAILDIR}/${jail}/var/log/lastlog")
    date_diff=$(( (cur_time - last_conn) / (60*60) ))

    check_file="${JAILDIR}/${jail}/etc/bkctld-check"
    if [ -f "${check_file}" ]; then
        critical_pattern="^\s*CRITICAL=[0-9]+"
        if grep -E "${critical_pattern}" "${check_file}"; then
            # shellcheck disable=SC2091
            CRITICAL=$(grep -E "${critical_pattern}" "${check_file}" | cut -d= -f2)
        else
            CRITICAL="${DEFAULT_CRITICAL}"
        fi
        warning_pattern="^\s*WARNING=[0-9]+"
        if grep -E "${warning_pattern}" "${check_file}"; then
            # shellcheck disable=SC2091
            WARNING=$(grep -E "${warning_pattern}" "${check_file}" | cut -d= -f2)
        else
            WARNING="${DEFAULT_WARNING}"
        fi
    fi

    if [ "${CRITICAL}" -gt "0" ] && [ "${date_diff}" -gt "${CRITICAL}" ]; then
        nb_crit=$((nb_crit + 1))
        output="${output}CRITICAL - ${jail} - ${date_diff} hours (critical: ${CRITICAL})\n"
        [ "${return}" -le 2 ] && return=2
    elif [ "${WARNING}" -gt "0" ] && [ "${date_diff}" -gt "${WARNING}" ]; then
        nb_warn=$((nb_warn + 1))
        output="${output}WARNING - ${jail} - ${date_diff} hours (warning: ${WARNING})\n"
        [ "${return}" -le 1 ] && return=1
    else
        nb_ok=$((nb_ok + 1))
        output="${output}OK - ${jail} - ${date_diff} hours (critical: ${CRITICAL}, warning: ${WARNING})\n"
    fi
}

for jail in $("${LIBDIR}/bkctld-list"); do
    if [ -f "${JAILDIR}/${jail}/var/log/lastlog" ]; then
        check_jail "${jail}"
    else
        nb_unkn=$((nb_unkn + 1))
        output="${output}UNKNOWN - ${jail} doesn't have lastlog !\n"
        [ "${return}" -le 3 ] && return=3
    fi
done

[ "${return}" -ge 0 ] && header="OK"
[ "${return}" -ge 1 ] && header="WARNING"
[ "${return}" -ge 2 ] && header="CRITICAL"
[ "${return}" -ge 3 ] && header="UNKNOWN"

printf "%s - %s UNK / %s CRIT / %s WARN / %s OK\n\n" "${header}" "${nb_unkn}" "${nb_crit}" "${nb_warn}" "${nb_ok}"

printf "${output}" | grep -E "^UNKNOWN"
printf "${output}" | grep -E "^CRITICAL"
printf "${output}" | grep -E "^WARNING"
printf "${output}" | grep -E "^OK"

exit "${return}"
