#!/bin/sh
#
# Update jail <jailname> or all
# Usage: update <jailname>|all
#

# shellcheck source=./config
LIBDIR="$(dirname $0)" && . "${LIBDIR}/includes"

jail_name="${1:-}"
if [ ! -n "${jail_name}" ]; then
    "${LIBDIR}/bkctld-help" && exit 1
fi
jail_path=$(jail_path "${jail_name}")

[ -d "${jail_path}" ] || error "${jail_name} : trying to update inexistant jail"

"${LIBDIR}/bkctld-is-on" "${jail_name}" && "${LIBDIR}/bkctld-stop" "${jail_name}"

setup_jail_chroot "${jail_name}"

notice "${jail_name} : jail has been updated."
