#!/bin/sh
#
# Remove jail <jailname> or all
# Usage: remove <jailname>|all
#

LIBDIR="$(dirname $0)" && . "${LIBDIR}/config"

jail="${1:-}"
if [ ! -n "${jail}" ]; then
    "${LIBDIR}/bkctld-help" && exit 1
fi
[ -d "${CONFDIR}/${jail}" ] || error "${jail} : trying to remove inexistant jail"
"${LIBDIR}/bkctld-is-on" "${jail}" && "${LIBDIR}/bkctld-stop" "${jail}"

"${LIBDIR}/bkctld-firewall" "${jail}"
rm -rf "${CONFDIR}/${jail}"
notice "${jail} : deleted jail"
if [ -d "${MOUNT_POINT}/${jail}" ]; then
    mv -T "${MOUNT_POINT}/${jail}" "${MOUNT_POINT}/${jail}.archived"
    mv -T "${LOGDIR}/${jail}" "${LOGDIR}/${jail}.archived"
    notice "${jail} was archived"
fi
