#!/bin/sh
#
# Reload jail <jailname> or all
# Usage: reload <jailname>|all
#

LIBDIR="$(dirname $0)" && . "${LIBDIR}/config"

jail="${1:-}"
if [ ! -n "${jail}" ]; then
    "${LIBDIR}/bkctld-help" && exit 1
fi
check_jail "${jail}" || error "${jail} : trying to reload inexistant jail"
check_jail_on "${jail}" || exit 0

pid=$(cat "${JAILDIR}/${jail}/${SSHD_PID}")

kill -HUP "${pid}" && notice "${jail} was reloaded [${pid}]"
