#!/bin/sh
#
# Update jail <jailname> or all
# Usage: update <jailname>|all
#

# shellcheck source=config
LIBDIR="$(dirname $0)" && . "${LIBDIR}/config"

jail="${1:-}"
if [ ! -n "${jail}" ]; then
    "${LIBDIR}/bkctld-help" && exit 1
fi
[ -d "${JAILDIR}/${jail}" ] || error "${jail} : trying to update inexistant jail"
"${LIBDIR}/bkctld-is-on" "${jail}" && "${LIBDIR}/bkctld-stop" "${jail}"

. "${LIBDIR}/mkjail"
notice "${jail} : updated jail"
