#!/bin/sh
#
# Description: Update binaries and libraries
# Usage: update [<jailname>|all]
#

# shellcheck source=./includes
LIBDIR="$(dirname $0)" && . "${LIBDIR}/includes"

jail_name="${1:?}"
if [ -z "${jail_name}" ]; then
    show_help && exit 1
fi
jail_path=$(jail_path "${jail_name}")

test -d "${jail_path}" || error "${jail_name}: jail not found" 2

# Ensure we manipulate jails in the current/compatible version format
test $(get_jail_version "${jail_name}") -ne ${CURRENT_JAIL_VERSION} && error "${jail_name}: jail needs to be updated to version ${CURRENT_JAIL_VERSION} (currently $(get_jail_version "${jail_name}")) - Use bkctld convert-v2 <jail>" 3

"${LIBDIR}/bkctld-is-on" "${jail_name}" 2>/dev/null
case "$?" in
    0)
        jail_initial_status="on"
    ;;
    100)
        jail_initial_status="off"
    ;;
    *)
        unset jail_initial_status
        error "Error evaluating jail '${jail_name}' state. bkctld-is-on exited with '$?'"
    ;;
esac

test "${jail_initial_status}" = "on" && "${LIBDIR}/bkctld-stop" "${jail_name}"

setup_jail_chroot "${jail_name}"

test "${jail_initial_status}" = "on" && "${LIBDIR}/bkctld-start" "${jail_name}"

notice "Update jail '${jail_name}' : OK"
