#!/bin/sh
#
# Description: Stop SSH server
# Usage: stop [<jailname>|all]
#

# shellcheck source=./includes
LIBDIR="$(dirname $0)" && . "${LIBDIR}/includes"

jail_name="${1:?}"
if [ -z "${jail_name}" ]; then
    show_help && exit 1
fi
jail_path=$(jail_path "${jail_name}")

test -d "${jail_path}" || error "${jail_name}: jail not found" 2

"${LIBDIR}/bkctld-is-on" "${jail_name}" || exit 0

if systemctl stop systemd-nspawn@${jail_name}; then
    notice "Stopped jail \`${jail_name}'"
else
    error "Stop jail \`${jail_name}' : failed"
fi
