#!/bin/sh
#
# Description: Show jail log (with journalctl)
# Usage: log <jailname>
#

set -eu

# shellcheck source=./includes
LIBDIR="$(dirname $0)" && . "${LIBDIR}/includes"

jail_name="${1:?}"
if [ -z "${jail_name}" ]; then
    show_help && exit 1
fi
jail_path=$(jail_path "${jail_name}")

test -d "${jail_path}" || error "${jail_name}: jail not found" 2

journalctl --reverse --unit systemd-nspawn@${jail_name}
