#!/bin/sh
#
# Description: Set or get ssh pubic key
# Usage: key <jailname> [<keyfile>]
#

# shellcheck source=./includes
LIBDIR="$(dirname $0)" && . "${LIBDIR}/includes"

jail_name="${1:?}"
keyfile="${2:-}"

if [ -z "${jail_name}" ]; then
    show_help && exit 1
fi
jail_rootfs_path=$(jail_rootfs_path "${jail_name}")

test -d "${jail_rootfs_path}" || error "${jail_name}: jail rootfs not found" 2

# Ensure we manipulate jails in the current/compatible version format
test "$(get_jail_version "${jail_name}")" -ne "${CURRENT_JAIL_VERSION}" && error "${jail_name}: jail needs to be uptated to version ${CURRENT_JAIL_VERSION} (currently $(get_jail_version "${jail_name}")) - Use bkctld convert-v2 <jail>" 3

if [ -z "${keyfile}" ]; then
    if [ -f "${jail_rootfs_path}/${AUTHORIZED_KEYS}" ]; then
        cat "${jail_rootfs_path}/${AUTHORIZED_KEYS}"
    fi
else
    test -r "${keyfile}" || error "SSH key '${keyfile}' for jail '${jail_name}' is missing or is not readable."
    cat "${keyfile}" > "${jail_rootfs_path}/${AUTHORIZED_KEYS}"
    chmod 600 "${jail_rootfs_path}/${AUTHORIZED_KEYS}"
    notice "Update SSH key '${keyfile}' for jail '${jail_name}' : OK"
fi
