#!/bin/sh
#
# Description: Check if a SSH server is on (exit 0) or not (exit 100)
# Usage: is-on <jailname>
#

# shellcheck source=./includes
LIBDIR="$(dirname $0)" && . "${LIBDIR}/includes"

jail_name="${1:?}"

if [ -z "${jail_name}" ]; then
    show_help && exit 1
fi
jail_path=$(jail_path "${jail_name}")

test -d "${jail_path}" || error "${jail_name}: jail not found" 2

# Error codes are references in "includes" file
return=100
if systemctl is-active --quiet systemd-nspawn@"${jail_name}"; then
     return=0
fi
exit "${return}"
