#!/bin/bash
#
#

case $1 in
   config)
        cat <<'UNLIKELY_EOF'
graph_title bkctld operations running
graph_vlabel Number of bkctld operations curently running
graph_args --lower-limit 0

graph_scale no
graph_category bkctld
graph_info The total number of bkctld operations curently running (being an bkctld inc or rm)

bkctld_inc.info bkctld inc running
bkctld_inc.label Number of inc operation currently running
bkctld_inc.draw AREA

bkctld_rm.info bkctld rm running
bkctld_rm.label Number of delete operation currently running
bkctld_rm.draw STACK


UNLIKELY_EOF
        exit 0;;
esac

bkctld_rm=$(ps aux | grep "bkctld-rm" | grep -v grep | wc -l)
bkctld_inc=$(ps aux | grep "bkctld-inc" | grep -v grep | wc -l)

# Normalize values; We can't have more than one inc or more than one rm
if [[ $bkctld_rm -gt 1 ]]; then
        bkctld_rm=1
fi
if [[ $bkctld_inc -gt 1 ]]; then
        bkctld_inc=1
fi

printf "bkctld_rm.value %s\n" $bkctld_rm
printf "bkctld_inc.value %s\n" $bkctld_inc



